regular_task_template: &REGULAR_TASK_TEMPLATE
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR != ''
  auto_cancellation: $CIRRUS_PR != ''
  env:
    CARGO_HUSKY_DONT_INSTALL_HOOKS: true
    CARGO_TERM_VERBOSE: true

task:
  << : *REGULAR_TASK_TEMPLATE
  name: FreeBSD 12.0
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    matrix:
      - RUST_TOOLCHAIN: beta
      - RUST_TOOLCHAIN: nightly
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  setup_script:
    - pkg install -y git pkgconf fusefs-libs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --default-toolchain $RUST_TOOLCHAIN --profile=minimal
  submodules_script:
    - git submodule update --init
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
