[package]
name = "polyfuse"
version = "0.1.0"
description = "Asynchronous FUSE (Filesystem in Userspace) framework"
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
futures-channel-preview = "0.3.0-alpha.19"
futures-io-preview = "0.3.0-alpha.19"
libc = "0.2"
log = "0.4"
memoffset = "0.5"
mio = "0.6"
smallvec = "0.6"

[dependencies.futures-util-preview]
version = "0.3.0-alpha.19"
features = ["unstable", "io", "select-macro"]

[dependencies.tokio-net]
version = "0.2.0-alpha.1"
features = ["signal"]

[dependencies.tokio-sync]
version = "0.2.0-alpha.6"

[dependencies.polyfuse-sys]
version = "0.1.0"
path = "polyfuse-sys"

[dependencies.polyfuse-abi]
version = "0.1.0"
path = "polyfuse-abi"

[dev-dependencies]
pretty_env_logger = "0.3"
tokio = "0.2.0-alpha.6"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [ "user-hooks" ]

[workspace]
members = [
  ".",
  "polyfuse-abi",
  "polyfuse-abi/systest",
  "polyfuse-sys",
]
