[package]
name = "polyfuse"
version = "0.1.0"
description = "Asynchronous FUSE (Filesystem in Userspace) framework"
publish = false
authors = [ "Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>" ]
edition = "2018"

[dependencies]
async-trait = "0.1"
bitflags = "1.2"
bytes = "0.4"
futures = { version = "0.3.0", features = [ "unstable", "async-await" ] }
lazy_static = "1"
libc = "0.2"
log = "0.4"
memoffset = "0.5"
mio = "0.6"
smallvec = "0.6"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "master" }

[dependencies.polyfuse-sys]
version = "0.1.0"
path = "polyfuse-sys"

[dev-dependencies]
anyhow = "1"
pretty_env_logger = "0.3"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [ "user-hooks" ]

[workspace]
members = [
  ".",
  "polyfuse-sys",
  "systest",
]
