name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose

  Lint:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Install components
      run: |
        rustup component add rustfmt clippy

    - name: Format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all

  DeployMasterDoc:
    runs-on: ubuntu-latest
    container:
      image: rustops/crates-build-env:latest
      options: --memory 3221225472
    steps:
    - uses: actions/checkout@v1

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    # TODO:
    # * restrict network access during building docs.
    # * restrict all write access expect target/
    - name: Build
      run: |
        set -ex
        cargo fetch --verbose
        timeout -sKILL 900 cargo doc --no-deps -p polyfuse-channel --verbose
        timeout -sKILL 900 cargo doc --no-deps -p polyfuse --all-features --verbose
        rm -rfv ./target/doc/.lock
        echo '<meta http-equiv="refresh" content="0;url=polyfuse">' > ./target/doc/index.html

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: published-docs
        path: target/doc

    - name: Deply to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc

  Coverage:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Install grcov
      run: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        mv -v ./grcov /usr/local/bin

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Run test (with coverage report)
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

    - name: Collect coverage reports
      uses: actions-rs/grcov@v0.1.2
      if: success()
      id: coverage

    - name: Send report to Codecov
      uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        file: ./lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
