name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_HUSKY_DONT_INSTALL_HOOKS: true
  CARGO_TERM_VERBOSE: true

jobs:
  Test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust_toolchain: [beta, nightly]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install APT dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust_toolchain }}
        override: true

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all

  Lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install APT dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: beta
        components: rustfmt, clippy
        override: true

    - name: Format check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all

  DeployMasterDoc:
    runs-on: ubuntu-18.04
    container:
      image: rustops/crates-build-env:latest
      options: --memory 3221225472
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    # TODO:
    # * restrict network access during building docs.
    # * restrict all write access expect target/
    - name: Build API docs
      run: bash ./scripts/gen_docs.sh

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: published-docs
        path: target/doc

    - name: Deply to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc

  Coverage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install APT dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev

    - name: Install grcov
      run: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        mkdir -pv $HOME/.grcov/bin
        mv -v ./grcov $HOME/.grcov/bin
        echo ::add-path::$HOME/.grcov/bin

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true

    - name: Run test (with generating coverage reports)
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

    - name: Collect coverage reports
      uses: actions-rs/grcov@v0.1.2
      if: success()
      id: coverage

    - name: Send report to Codecov
      uses: codecov/codecov-action@v1.0.3
      if: success()
      with:
        file: ./lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
