name: Actions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev
        rustup component add clippy rustfmt

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose

    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all

    - name: Build API doc
      run: |
        cargo doc --no-deps -p fuse-async --all-features --verbose
        cargo doc --no-deps -p fuse-async-channel --verbose
        echo '<meta http-equiv="refresh" content="0;url=fuse_async">' > ./target/doc/index.html
    - name: Deply API doc
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc

  Coverage:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        mv -v ./grcov /usr/local/bin

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose
      env:
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

    - uses: actions-rs/grcov@v0.1.2
      if: success()
      id: coverage

    - uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        file: ./lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
