name: Actions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev
        rustup component add clippy rustfmt

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --verbose

    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all

    - name: Build API doc
      run: |
        cargo doc -p fuse-async-abi --verbose
        cargo doc -p fuse-async --all-features --verbose
        cargo doc -p fuse-async-channel --verbose
        echo '<meta http-equiv="refresh" content="0;url=fuse_async">' > ./target/doc/index.html
    - name: Deply API doc
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc

  Tarpaulin:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:latest-nightly
      options: --security-opt seccomp=unconfined
    steps:
    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             libfuse-dev \
             udev \
             libudev-dev
    - name: Run coverage test
      continue-on-error: true
      run: |
        cargo tarpaulin --out Xml --all --verbose

    - uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
