name: Actions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Linux:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update -yqq
        apt-get install -yqq --no-install-recommends \
             build-essential \
             pkg-config \
             llvm-dev \
             libclang-dev \
             clang \
             libfuse-dev \
             udev \
             libudev-dev \
             libssl-dev \
             cmake \
             zlib1g-dev
        cargo install --debug cargo-tarpaulin
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Run coverage test
      run: cargo tarpaulin --out Xml --all --verbose
    - uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Build API doc
      run: |
        cargo doc -p fuse-async-abi --verbose
        cargo doc -p fuse-async --all-features --verbose
        cargo doc -p fuse-async-channel --verbose
        echo '<meta http-equiv="refresh" content="0;url=fuse_async">' > ./target/doc/index.html
    - name: Deply API doc
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc